### ISSUE TITLE
crash in vignette example

### ISSUE THREAD

**Issue by oscci** [moshagen/semPower#1]
Code chunk on line 239
# perform a priori power analysis
ap6 <- semPower.aPriori(SigmaHat = list(cov.h0.g1, cov.h0.g2), 
                        Sigma = list(cov.pop.g1, cov.pop.g2), 
                        alpha = .05, beta = .20, N = list(1, 1), df = df)

summary(ap6)
Gives crash with : Error in semPower.aPriori(SigmaHat = list(cov.h0.g1, cov.h0.g2), Sigma = list(cov.pop.g1,  : 
  unused argument (N = list(1, 1)). Removing N=list(1,1) does not fix it.

**Comment by moshagen** [comment]
Did you use the CRAN or the github version? Multiple group cases are not yet on CRAN.

**Comment by oscci** [comment]
ah I should have thought of that. thanks. will install from github. v useful resource!

Sent from my iPad

On 11 Aug 2020, at 20:24, moshagen <notifications@github.com> wrote:

﻿

Did you use the CRAN or the github version? Multiple group cases are not yet on CRAN.

**Comment by moshagen** [comment]
Thank you anyway for reminding me to push the updates on CRAN, should be online in about 3 weeks (holiday season strikes CRAN submissions, too).

**Comment by moshagen** [comment]
Now on CRAN.
