### ISSUE TITLE
What is the meaning of RMSEA in Model-based power analyses.

### ISSUE THREAD

**Issue by St-ZFeng** [moshagen/semPower#25]
Hello! I tried using this powerful R package, but encountered some confusing issues, about the meaning of RMSEA displayed in the Model-based power analyses' results. I have a serial mediation model and am attempting to conduct a post hoc analysis. The fit indices for the entire model show an RMSEA of 0.044. However, when calculating the power to detect whether one of the indirect paths is zero, the RMSEA shows as 0.45, which is much larger than the typically mentioned 0.05. Is this RMSEA different from that of the overall model fit? In other words, does it signify differences between models where one has an indirect path set to zero and one doesn't, with a larger value indicating greater disparities?

Furthermore, I'm somewhat doubtful if this approach is correct because while power calculated through Model-free analyses yields a very small value, Model-based power analyses show a power as high as 0.98.

I have read through the manual, but please forgive me for being a novice in this area.

![image](https://github.com/moshagen/semPower/assets/113660099/45abec14-c263-423d-be9e-8ef511228161)

**Comment by moshagen** [comment]
yes, you have just a single df when testing an indirect effect, but probably many more when testing the full model. The RMSEA scales F0 by the df, and is often large when there a few df. In your case, the RMSEA is simply the square root fof F0, i.e. sqrt(.200310)
