### ISSUE TITLE
Error in semPower.powerLav

### ISSUE THREAD

**Issue by MTbaX** [moshagen/semPower#26]
Hi!
I'm relatively new to computing simulated power analysis, which may explain why I cannot solve this problem.
I hope you'll be able to help me.

I experienced this error

"Error in semPower.aPriori(...) : 
  The required N of 38 is most likely smaller than twice the number of variables. Simulated a priori power will probably not work in this case. If N exceeds p, you can try a simulated post-hoc analyses."

when I was conducting a power analysis using semPower.powerLav with simulated data. 
When I only compute an analytical power analysis, everything works fine, and I get a reasonable result, as in the image below.
<img width="1592" alt="grafik" src="https://github.com/user-attachments/assets/004e5678-5989-4aea-9c49-b93d19d0f021">

I tried raising the required N manually by overwriting it in the SimResult object, but that did not work.
However, when simulating, I get the error quoted above and do not know how to solve it.

Thank you very much in advance!

Those are the models and the code I used:
# population model
popModel <- '
# measurement model with altered loadings
y1 =~ 0.9*x1 + 0.8*x2 + 0.7*x3  
y2 =~ 0.8*x4 + 0.7*x5 + 0.6*x6
y3 =~ 0.7*x7 + 0.6*x8 + 0.5*x9
y4 =~ 0.9*x10 + 0.8*x11 + 0.7*x12
y5 =~ 0.8*x13 + 0.7*x14 + 0.6*x15
y6 =~ 0.9*x16 + 0.8*x17 + 0.7*x18
y7 =~ 0.7*x19 + 0.6*x20 + 0.5*x21
y8 =~ 0.9*x22 + 0.8*x23 + 0.7*x24
y9 =~ 0.8*x25 + 0.7*x26 + 0.6*x27
y10 =~ 0.9*x28 + 0.8*x29 + 0.7*x30

y11 =~ 0.9*x31 + 0.8*x32 + 0.7*x33
y12 =~ 0.7*x34 + 0.6*x35 + 0.5*x36
y13 =~ 0.8*x37 + 0.7*x38 + 0.6*x39
y14 =~ 0.9*x40 + 0.8*x41 + 0.7*x42
y15 =~ 0.7*x43 + 0.6*x44 + 0.5*x45
y16 =~ 0.8*x46 + 0.7*x47 + 0.6*x48
y17 =~ 0.9*x49 + 0.8*x50 + 0.7*x51
y18 =~ 0.8*x52 + 0.7*x53 + 0.6*x54

y19 =~ 0.8*x55 + 0.7*x56 + 0.6*x57
y20 =~ 0.8*x58 + 0.7*x59 + 0.6*x60
y21 =~ 0.8*x61 + 0.7*x62 + 0.6*x63
y22 =~ 0.8*x64 + 0.7*x65 + 0.6*x66

# variances of latent variables (set to 1 for simplicity)
y1 ~~ 1*y1
y2 ~~ 1*y2
y3 ~~ 1*y3
y4 ~~ 1*y4
y5 ~~ 1*y5
y6 ~~ 1*y6
y7 ~~ 1*y7
y8 ~~ 1*y8
y9 ~~ 1*y9
y10 ~~ 1*y10
y11 ~~ 1*y11
y12 ~~ 1*y12
y13 ~~ 1*y13
y14 ~~ 1*y14
y15 ~~ 1*y15
y16 ~~ 1*y16
y17 ~~ 1*y17
y18 ~~ 1*y18
y19 ~~ 1*y19
y20 ~~ 1*y20
y21 ~~ 1*y21
y22 ~~ 1*y22

# covariances (moderate values)
y1 ~~ 0.4*y2
y3 ~~ 0.3*y4
y6 ~~ 0.4*y7
y9 ~~ 0.3*y10
y19 ~~ 0.1*y18
y20 ~~ 0.1*y22

# regressions (adjusted coefficients)
y11 ~ 0.5*y18 + 0.4*y15 + 0.6*y14 + 0.3*y13 + 0.7*y12 + 0.8*y19 + 0.4*y21 + 0.7*y22
y5 ~ 0.4*y2 + 0.5*y1 + 0.6*y3 + 0.3*y4 + 0.4*y6 + 0.5*y7 + 0.4*y8 + 0.3*y18 + 0.6*y20
y6 ~ 0.6*y3 + 0.4*y4 + 0.5*y9 + 0.3*y10 + 0.5*y18 + 0.6*y16 + 0.7*y17 + 0.4*y14 + 0.5*y13 + 0.6*y15
y7 ~ 0.5*y3 + 0.6*y4 + 0.7*y9 + 0.8*y10 + 0.5*y18 + 0.4*y16 + 0.5*y17 + 0.4*y14 + 0.6*y12
y8 ~ 0.7*y9 + 0.6*y10 + 0.5*y6 + 0.4*y7 + 0.3*y3 + 0.4*y4 + 0.5*y18
'

# analysis model
mod <- '
# measurement model (including dummy latent variables to match the dimensionality)
y1 =~ 1*x1 + x2 + x3
y2 =~ 1*x4 + x5 + x6
y3 =~ 1*x7 + x8 + x9
y4 =~ 1*x10 + x11 + x12
y5 =~ 1*x13 + x14 + x15
y6 =~ 1*x16 + x17 + x18
y7 =~ 1*x19 + x20 + x21
y8 =~ 1*x22 + x23 + x24
y9 =~ 1*x25 + x26 + x27
y10 =~ 1*x28 + x29 + x30

y11 =~ 0*x31 + 0*x32 + 0*x33  # Dummy latent variable
y12 =~ 0*x34 + 0*x35 + 0*x36  # Dummy latent variable
y13 =~ 0*x37 + 0*x38 + 0*x39  # Dummy latent variable
y14 =~ 0*x40 + 0*x41 + 0*x42  # Dummy latent variable
y15 =~ 0*x43 + 0*x44 + 0*x45  # Dummy latent variable
y16 =~ 0*x46 + 0*x47 + 0*x48  # Dummy latent variable
y17 =~ 0*x49 + 0*x50 + 0*x51  # Dummy latent variable
y18 =~ 0*x52 + 0*x53 + 0*x54  # Dummy latent variable

y19 =~ 0*x55 + 0*x56 + 0*x57  # Dummy latent variable
y20 =~ 0*x58 + 0*x59 + 0*x60  # Dummy latent variable
y21 =~ 0*x61 + 0*x62 + 0*x63  # Dummy latent variable
y22 =~ 0*x64 + 0*x65 + 0*x66  # Dummy latent variable

# variances of latent variables (set to 1 for consistency)
y1 ~~ 1*y1
y2 ~~ 1*y2
y3 ~~ 1*y3
y4 ~~ 1*y4
y5 ~~ 1*y5
y6 ~~ 1*y6
y7 ~~ 1*y7
y8 ~~ 1*y8
y9 ~~ 1*y9
y10 ~~ 1*y10

y11 ~~ 0*y11
y12 ~~ 0*y12
y13 ~~ 0*y13
y14 ~~ 0*y14
y15 ~~ 0*y15
y16 ~~ 0*y16
y17 ~~ 0*y17
y18 ~~ 0*y18
y19 ~~ 0*y19
y20 ~~ 0*y20
y21 ~~ 0*y21
y22 ~~ 0*y22

# regressions (trivial or null regressions to maintain structure)
y4 ~ y1 + y2 + y3 + y5 + y6 + y7
y5 ~ y2 + y3 + y8 + y9
y6 ~ y2 + y3 + y8 + y9
y7 ~ y8 + y9 + y5 + y6 + y2 + y3
y8 ~ 0*y9 + 0*y10 + 0*y6 + 0*y7 + 0*y3 + 0*y4 + 0*y18

# Add trivial paths or covariances to ensure dimensional alignment
y11 ~ 0*y1 + 0*y2
y12 ~ 0*y3 + 0*y4
y13 ~ 0*y5 + 0*y6
y14 ~ 0*y7 + 0*y8
y15 ~ 0*y9 + 0*y10
y16 ~ 0*y11 + 0*y12
y17 ~ 0*y13 + 0*y14
y18 ~ 0*y15 + 0*y16
y19 ~ 0*y17 + 0*y18
y20 ~ 0*y19 + 0*y20
y21 ~ 0*y21 + 0*y22
y22 ~ 0*y1 + 0*y2 + 0*y3 + 0*y4 + 0*y5 + 0*y6
'

# computing Sigma
powerSEM <- semPower.powerLav( 
  type = "a-priori",
  alpha = .05,
  power = .90,
  modelPop = popModel,
  modelH0 = mod_0,
  simulatedPower = F
)

## simulation
set.seed(12345)
# power analysis
powerLav = semPower.powerLav( 
  type = "a-priori",
  alpha = .05,
  beta = .01,
  N = 100,
  modelH0 = mod_0_sigma,
  fitH1model = TRUE,
  Sigma = powerSEM$Sigma,
  simulatedPower = TRUE,
  simOptions = list( 
    nReplications = 1000,
    N = 2500,
    # normal distribution or non-normal
    type = "normal",
    missingMechanism = "MCAR",
    # parallel processing
    nCores = 10
    )

**Comment by moshagen** [comment]
When performing a simulated power analysis, data are generated and a model is fit to the generated data. The latter typically does not succeed when the number of manifest variables exceeds the number of observations. The message is telling you that you likely obtain the desired power of .90 with less than the observed number of variables and thus refuses to go on. Note that the sample size to obtain a certain level of power is a different issue from having a sufficiently large sample to support model estimation.

You could do a simulated post-hoc power analysis setting N to a number larger than the number of variables to verify that power is indeed higher than you initially requested. For instance, the following should yield a power > .90:

`
powerLav = semPower.powerLav(
type = "ph",
alpha = .05,
N = 200,
modelH0 = mod_0_sigma,
fitH1model = TRUE,
Sigma = powerSEM$Sigma,
simulatedPower = TRUE,
simOptions = list(
nReplications = 1000,
nCores = 10
)
)
`

**Comment by MTbaX** [comment]
Thank you so much for your answer! Due to the complexity of the models, I assumed this was very unlikely to happen and thought I might have made a mistake. 
I will try your suggested approach.
Again, thank you for your help.
